---
name: haproxy

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: haproxy
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: haproxy
    release: haproxy
    properties:
      ha_proxy:
        backend_port: ((haproxy-backend-port))
        backend_servers: ((haproxy-backend-servers))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name: bpm
  version: 1.1.8
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.8
  sha1: c956394fce7e74f741e4ae8c256b480904ad5942
- name: haproxy
  version: 10.0.0
  url: https://github.com/cloudfoundry-incubator/haproxy-boshrelease/releases/download/v10.0.0/haproxy-10.0.0.tgz
  sha1: 8c485beb92dceb4e2a78c4b540b2d0506684b9a8
